### ISSUE TITLE
Validation failure on the sample json

### ISSUE THREAD

**Issue by drorata** [kelvintaywl/jsonresume-validator#5]
I tried to validate the json provided with the cli tool and it didn't pass. Any idea?

**Comment by kelvintaywl** [comment]
hi @drorata ! would you be able to provide the sample used by you?

this could be possible as I'm trying to refine the validations to be less strict (e.g., work experiences need not have to have an end date) 🙇

**Comment by drorata** [comment]
Here's the file I used: https://gist.github.com/drorata/140e1c2a371fd11e3c659f2b7395221a#file-sample-json

**Comment by kelvintaywl** [comment]
@drorata 

thank you for the sample! it turns out that the validation was strict in asserting that the urls provided must be non-empty and valid urls. I have updated them to be less strict in that unless it is empty string, it must be a valid URL.

Have included your sample JSON as part of the tests in the PR @ https://github.com/kelvintaywl/jsonresume-validator/pull/6

thanks again! :)

**Comment by drorata** [comment]
Can I already update it from pip? Or should I do something else?

**Comment by kelvintaywl** [comment]
sure! please update with pip. you should be able to get the freshest version 0.1.3 :)
